[package]
name = "amethyst_parser_syn"
version = "0.1.0"
authors = ["benjamin"]
edition = "2018"

[dependencies]
syn = { version = "0.15", features = ["full", "visit", "parsing", "clone-impls", "extra-traits"], default-features = false }
proc-macro2 = "0.4.24"
clap = "2.32"
